# Generated by Django 4.1.7 on 2023-03-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_alter_servicios_contenido_alter_servicios_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='contenido',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
