# Generated by Django 4.1.7 on 2023-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_alter_servicios_contenido_alter_servicios_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='contenido',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
