# Generated by Django 4.1.7 on 2023-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_alter_servicios_contenido_alter_servicios_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='updated',
            field=models.DateTimeField(blank=True),
        ),
    ]
