# Generated by Django 4.1.7 on 2023-03-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_categorias_post_cates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorias',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cates',
            new_name='categorias',
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.CharField(max_length=100),
        ),
    ]
